# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_calculate_features.ipynb.

# %% auto 0
__all__ = ['generate_stat_features', 'window_walk']

# %% ../nbs/01_calculate_features.ipynb 4
import numpy as np

# %% ../nbs/01_calculate_features.ipynb 6
def rmssd(diff):
    val = 0.0
    for i in diff:
        val += float(i * i)
    if len(diff) == 0:
        return 0
    return np.sqrt(val / float(len(diff)))

# %% ../nbs/01_calculate_features.ipynb 7
def generate_stat_features(signal):

    mean = np.mean(signal)
    std = np.std(signal)
    median = np.median(signal)
    max = np.max(signal)
    min = np.min(signal)
    per_20 = np.percentile(signal, 20)
    per_80 = np.percentile(signal, 80)
    diff = [t - s for s, t in zip(signal, signal[1:])]
    rMSSD = rmssd(diff)

    row = [mean, std, median, max, min,
           per_20, per_80, rMSSD]

    return row

# %% ../nbs/01_calculate_features.ipynb 9
def window_walk(df_ibi, window=60, step=1, column="RR"):

    if df_ibi.empty:
        return []
    start = min(df_ibi['timestamp'])
    end = start + window
    terminal = max(df_ibi['timestamp'])
    rows = []
    
    while end <= terminal:

        subset_ibi = df_ibi[df_ibi['timestamp'] >= start]
        subset_ibi = subset_ibi[subset_ibi['timestamp'] <= end]
        
        if subset_ibi.shape[0] > 5:

            row = generate_stat_features(subset_ibi[column].values)
            row.insert(0, end)
            rows.append(row)
        
        start = start + step
        end = end + step

    return(rows)
