# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_load_model.ipynb.

# %% auto 0
__all__ = ['load', 'example_data']

# %% ../nbs/00_load_model.ipynb 3
import pickle as p
import pandas as pd
import os

# %% ../nbs/00_load_model.ipynb 4
def load(signal="rr"):
    print("loading model")
    this_dir, _ = os.path.split(__file__)  # Get path of this module
    
    if signal == "rr":
        data_path = os.path.join(this_dir, "model-SVM_type-classifier_task-stressprediction_features-rrinterval_v0.1.pickle")
    elif signal == "hr":
        data_path = os.path.join(this_dir, "model-SVM_type-classifier_task-stressprediction_features-heartrate_v0.1.pickle")
    elif signal == "both":
        data_path = os.path.join(this_dir, "model-SVM_type-classifier_task-stressprediction_features-hr-rri_v0.1.pickle")
    else:
        raise ValueError("Signal must be one of \"rr\", \"hr\", or \"both\"")
    
    model = p.load(open(data_path, 'rb'))
    return model

# %% ../nbs/00_load_model.ipynb 6
def example_data(signal="rr"):
    print("loading example data")
    this_dir, this_filename = os.path.split(__file__)  # Get path of this module

    if signal == "rr":
        data_path = os.path.join(this_dir, "example_rr.csv")
    elif signal == "hr":
        data_path = os.path.join(this_dir, "example_hr.csv")
    else:
        raise ValueError("Signal must be one of \"rr\" or \"hr\"")
    
    df = pd.read_csv(data_path)
    return df
