# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_model.ipynb.

# %% auto 0
__all__ = ['load']

# %% ../nbs/00_model.ipynb 3
import pickle as p
import os

# %% ../nbs/00_model.ipynb 4
def load():
    print("loading model")
    this_dir, this_filename = os.path.split(__file__)  # Get path of this module
    data_path = os.path.join(this_dir, "model-SVM_type-classifier_task-stressprediction_features-rrinterval_v0.1_.pickle")
    model = p.load(open(data_path, 'rb'))
