# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_preprocess.ipynb.

# %% auto 0
__all__ = ['preprocess_rr_df', 'preprocess_hr_df']

# %% ../nbs/02_preprocess.ipynb 3
import numpy as np

# %% ../nbs/02_preprocess.ipynb 5
# Helper functions
def calc_mad(temp_rr):
    median = np.nanmedian(temp_rr)
    dev = []
    for r in temp_rr:
        dev.append(np.abs(r - median))
    return np.nanstd(dev)


def handle_outliers(values, threshold=3):
    median = np.median(values)
    mad = calc_mad(values)
    lower_limit = median - threshold * mad
    upper_limit = median + threshold * mad
    cleaned = []
    for v in values:
        if lower_limit <= v <= upper_limit:
            cleaned.append(v)

    return cleaned, np.mean(cleaned), np.std(cleaned)

# %% ../nbs/02_preprocess.ipynb 6
def normalize_rr(values, threshold):

    rr_array = []
    data = values

    for rr in data:
        if 0.250 < rr < 2.500:
            rr_array.append(rr)

    cleaned_rr, mean_rr, std_rr = handle_outliers(rr_array, threshold)

    cleaned_ibi_signal = []
    index = []

    for val in data:
        if val in cleaned_rr:
            norm_rr = float(val - mean_rr) / std_rr
            cleaned_ibi_signal.append(norm_rr)
            index.append(True)
        else:
            index.append(False)
    return cleaned_ibi_signal, index

def normalize_hr(values, threshold):

    hr_array = []
    data = values

    for hr in data:
        if 25 < hr < 230:
            hr_array.append(hr)

    valid_hr, mean_hr, std_hr = handle_outliers(hr_array, threshold)

    cleaned_hr_signal = []

    index = []

    for val in data:
        if val in valid_hr:
            norm_hr = float(val - mean_hr) / std_hr
            cleaned_hr_signal.append(norm_hr)
            index.append(True)
        else:
            index.append(False)

    return cleaned_hr_signal, index

# %% ../nbs/02_preprocess.ipynb 7
def preprocess_rr_df(rr_df, rr_column="RR", mad_threshold=3):

    clean_rr_signal, index = normalize_rr(rr_df[rr_column], threshold=mad_threshold)
    clean_df = rr_df[index]
    clean_df[rr_column] = clean_rr_signal

    return clean_df

#| export

def preprocess_hr_df(hr_df, hr_column="HR", mad_threshold=3):

    clean_hr_signal, index = normalize_hr(hr_df[hr_column], threshold=mad_threshold)
    clean_df = hr_df[index]
    clean_df[hr_column] = clean_hr_signal

    return clean_df
